version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: book-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin12345
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/book-store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Admin12345
    depends_on:
      - postgres

volumes:
  postgres_data:

